# pandas will be imported and used throughout this file to manage the ACCT dataframe

## The data that will be used will come from Fall 2022's grade distribution and it will be interpreted by pandas as a csv file, and regular expressions will be used to clean the data from the spreadsheet to fit the project's purpose

In [2]:
import pandas as pd
import re
url = "https://docs.google.com/spreadsheets/d/1mS6khEB6m8cPNenNvY9Tg6bJ6YkmcvCI/export?format=csv&gid=1283335856"
df = pd.read_csv(url)

### Only a certain amount of columns may be analyzed from the spreadsheet. This includes the official grades, professor, and general class information

In [4]:
valid_columns = ["SUBJECT", "NBR", "COURSE NAME", "PROF", "TOTAL", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "F", "W", "AVG GPA"]
analysis_df = df[valid_columns]

### This analysis will only take into account the classes from the ACCT subject, so a separate dataframe must be created. After that, an option must be set so whenever the dataframe is called, it will display as many rows as possible

In [5]:
ACCT_df = analysis_df.loc[analysis_df["SUBJECT"] == "ACCT"]
pd.set_option('display.max_rows', None)
ACCT_df

,SUBJECT,NBR,PROF,TOTAL,A+,A,A-,B+,B,B-,C+,C,C-,D,F,W,AVG GPA
0,ACCT,100,"HO, V",28,0,11,2,1,3,3,0,3,0,0,0,5,3.383
1,ACCT,101,"CHAN, J",29,0,13,2,0,4,5,0,0,1,0,0,3,3.464
2,ACCT,101,"RUTHIZER, S",50,2,9,14,6,4,5,0,1,0,3,2,3,3.176
3,ACCT,101,"GRUZA, M",45,1,2,3,1,5,0,6,0,0,0,0,25,3.067
4,ACCT,101,"FEISULLIN, A",45,4,6,1,7,5,0,6,9,1,1,0,4,2.908
5,ACCT,101,"COWAN DOCKERY, M",45,6,1,1,4,3,2,2,11,0,0,1,9,2.771
6,ACCT,101,"THALER, M",45,0,0,4,5,7,4,5,9,0,1,0,8,2.674
7,ACCT,101,"SOLARSH, E",45,3,4,2,3,2,3,1,6,7,0,2,9,2.594
8,ACCT,101,"SOLARSH, E",45,4,1,3,3,7,2,0,8,5,0,3,6,2.553
9,ACCT,101,"DAUBER, N",50,2,0,1,3,7,2,2,7,3,6,6,10,1.992
10,ACCT,102,"FEISULLIN, A",40,7,1,2,2,6,6,3,1,4,0,0,8,2.997
11,ACCT,102,"RUTHIZER, S",46,1,1,6,12,7,7,4,3,0,4,0,1,2.864
12,ACCT,102,"RUBIN, M",22,2,2,0,2,2,3,1,1,4,3,0,2,2.540
13,ACCT,102,"DAVID, A",29,0,2,2,1,6,2,5,4,0,3,1,3,2.485
14,ACCT,102,"GRUZA, M",15,1,1,0,2,0,1,0,0,0,0,2,8,2.471
15,ACCT,102,"DAVID, A",34,0,2,1,3,7,4,2,6,3,2,2,2,2.409
16,ACCT,201,"HEASLIP, K",36,1,6,4,1,2,4,5,4,3,1,1,4,2.766
17,ACCT,201,"HEASLIP, K",12,0,0,1,0,0,4,0,0,4,1,0,2,2.230
18,ACCT,201,"COWAN DOCKERY, M",21,0,1,0,0,0,0,4,9,0,0,0,7,2.229
19,ACCT,201,"MAZZO, M",36,0,3,0,2,4,1,7,0,0,0,7,12,2.058
20,ACCT,202,"KUMAR, V",11,0,5,0,0,0,0,0,0,0,0,0,6,4.000
21,ACCT,202,"ROSANO, E",34,1,14,0,1,10,0,3,2,0,0,1,2,3.256
22,ACCT,202,"SCHWALB, H",16,0,2,0,6,0,2,0,2,0,1,0,3,2.938
23,ACCT,202,"SCHWALB, H",18,0,2,1,2,3,2,0,4,0,0,0,4,2.907
24,ACCT,202,"ROSANO, E",28,3,8,0,2,2,0,1,6,0,1,3,2,2.765
25,ACCT,202,"HEASLIP, K",31,1,0,2,3,2,2,2,3,1,1,3,10,2.300
26,ACCT,261,"STEIN, R",44,1,9,7,10,4,0,0,0,0,0,0,7,3.577
27,ACCT,261,"STEIN, R",25,3,0,8,5,7,2,0,0,0,0,0,0,3.380
28,ACCT,261,"ALTMAN, J",45,2,6,5,8,6,6,4,4,0,1,1,2,3.007
29,ACCT,261,"ALTMAN, J",39,0,0,4,10,7,3,3,5,0,3,2,2,2.616
30,ACCT,261,"SEYMORE, J",11,0,2,1,1,0,1,1,2,1,0,1,1,2.570
31,ACCT,261,"LEIBOWICZ, B",43,1,2,2,0,3,6,3,13,0,8,1,3,2.192
32,ACCT,261,"LEIBOWICZ, B",38,0,1,1,2,5,0,4,10,0,6,3,2,2.016
33,ACCT,305,"COHEN, M",45,0,13,6,8,5,7,0,1,0,0,1,4,3.329
34,ACCT,305,"SUN, F",27,0,13,5,0,1,1,1,2,0,1,2,0,3.212
35,ACCT,305,"QURESHI, A",27,3,2,3,4,4,3,0,5,0,0,1,2,2.976
36,ACCT,305,"COHEN, M",31,1,1,0,9,4,4,3,3,0,0,0,6,2.936
37,ACCT,306,"ADELBERG, A",35,12,16,1,0,0,1,1,0,0,0,0,3,3.894
38,ACCT,306,"ADELBERG, A",34,7,6,4,6,10,0,0,0,0,0,0,1,3.533
39,ACCT,306,"STEVENS, M",32,0,1,1,4,7,9,5,5,0,0,0,0,2.741
40,ACCT,306,"STEVENS, M",18,0,1,0,2,4,5,4,0,1,0,1,0,2.611
41,ACCT,311,"BALKARAN, D",27,0,3,6,5,2,2,1,2,0,1,1,4,3.017
42,ACCT,311,"SATENSTEIN, J",31,5,3,0,4,4,1,2,10,0,1,1,0,2.758
43,ACCT,311,"SATENSTEIN, J",31,3,3,1,0,3,5,2,8,0,3,2,1,2.460
44,ACCT,311,"HUANG, Q",12,1,1,0,1,1,2,1,1,0,2,1,1,2.364
45,ACCT,321,"SOLIERI, S",29,9,4,4,1,2,1,1,4,0,0,1,2,3.300
46,ACCT,321,"FITZSIMONS, S",13,0,0,0,4,5,1,1,1,0,0,0,1,2.933
47,ACCT,321,"KUMAR, V",29,0,2,0,0,19,0,0,6,0,0,0,2,2.852
48,ACCT,321,"DAUBER, N",47,0,4,3,3,11,3,2,6,1,10,4,0,2.264
49,ACCT,322,"QAMAR, Z",14,0,3,4,2,4,0,0,0,0,0,0,1,3.492
50,ACCT,322,"QAMAR, Z",15,1,5,0,2,4,2,1,0,0,0,0,0,3.353
51,ACCT,322,"DAUBER, N",30,6,1,1,1,3,6,6,5,0,1,0,0,2.833
52,ACCT,322,"HITZIG, N",11,0,1,0,0,2,0,3,2,0,0,0,3,2.613
53,ACCT,322,"HITZIG, N",10,0,1,0,2,2,2,0,1,0,2,0,0,2.600
54,ACCT,341,"SOLIERI, S",23,6,3,1,2,2,2,1,3,0,0,2,1,3.000
55,ACCT,343,"QURESHI, A",34,1,29,0,0,0,0,0,0,0,0,0,4,4.000
56,ACCT,350,"SILVERMAN, A",20,3,1,0,1,3,1,3,5,0,0,0,3,2.818
57,ACCT,362,"KATZ, J",29,7,5,2,1,4,2,2,4,0,0,2,0,3.059
58,ACCT,362,"ALTMAN, J",21,1,3,2,1,8,2,0,3,0,1,0,0,3.005
59,ACCT,363,"HERCZOG, L",13,0,5,4,4,0,0,0,0,0,0,0,0,3.692
60,ACCT,363,"LINN, D",13,0,4,1,1,2,0,1,1,1,0,0,1,3.182
61,ACCT,367,"BLUMENFRUCHT, I",19,2,4,5,2,1,1,2,0,0,0,0,1,3.494
62,ACCT,367,"BARONE, E",35,2,6,5,5,6,1,3,5,0,0,2,0,2.989
63,ACCT,367,"BLUMENFRUCHT, I",36,4,2,2,4,5,7,6,4,0,0,0,1,2.950
64,ACCT,367,"BARONE, E",20,3,1,1,2,4,0,4,3,0,2,0,0,2.775
65,ACCT,367,"CALAMARI, J",27,2,2,1,3,4,2,3,6,2,1,0,1,2.704
66,ACCT,367,"LEIBOWICZ, B",26,1,2,2,1,3,3,2,5,0,2,0,3,2.686
67,ACCT,372,"BALKARAN, D",45,0,7,8,10,10,3,0,3,0,0,1,3,3.207
68,ACCT,372,"XIAO, J",22,1,1,4,1,3,3,1,4,1,1,0,2,2.810
69,ACCT,372,"XIAO, J",16,1,0,1,0,5,0,4,0,1,2,1,1,2.373
70,ACCT,372,"SILVERMAN, A",37,4,2,1,2,6,2,5,3,0,3,7,2,2.234
71,ACCT,712,"HUANG, Q",20,9,5,3,3,0,0,0,0,0,0,0,0,3.850
72,ACCT,712,"HITZIG, N",22,0,1,4,0,3,6,3,0,4,0,0,1,2.748
73,ACCT,723,"ZARATE, G",20,5,7,7,1,0,0,0,0,0,0,0,0,3.860
74,ACCT,723,"ZARATE, G",22,5,9,5,3,0,0,0,0,0,0,0,0,3.836
75,ACCT,747,"NIGRELLI, U",60,60,0,0,0,0,0,0,0,0,0,0,0,4.000
76,ACCT,748,"SUH, J",22,17,2,0,0,1,0,0,0,0,0,2,0,3.591
77,ACCT,757,"BALKARAN, D",20,0,2,4,7,2,3,0,0,0,0,0,1,3.333
78,ACCT,757,"MAZZO, M",14,0,1,1,3,2,1,5,0,0,0,0,1,2.908
79,ACCT,758,"AHRONI, S",32,0,17,6,2,7,0,0,0,0,0,0,0,3.681
80,ACCT,759,"AHRONI, S",36,0,21,3,6,6,0,0,0,0,0,0,0,3.692
81,ACCT,785,"XIAO, J",17,5,7,3,0,2,0,0,0,0,0,0,0,3.829
82,ACCT,785,"SUH, J",26,16,3,1,3,0,2,0,0,0,0,0,1,3.800
83,ACCT,362W,"LINN, D",25,0,3,4,4,3,1,2,1,1,0,0,2,3.158
84,ACCT,362W,"SEYMORE, J",12,0,1,1,2,2,1,0,2,0,0,0,3,3.000

### From this, it can be concluded that the ACCT has no classes where the GPA is 0 so there are no null values. However, the data contains data for non-undergraduate classes, so it must be cleaned by using regular expressions

In [6]:
# The class number must start with a digit from 1-3, followed by 2 digits from 0-9
# The number can also have a W at the end to represent writing-intensive classes

CourseNumberPattern = r'^[1-3][0-9]{2}W?$'

mask = ACCT_df['NBR'].str.contains(CourseNumberPattern) # Finds what rows match the regular expression pattern

In [7]:
ACCT_df = ACCT_df[mask] # If mask is false, the rows must be entirely removed from the dataframe to prevent false results
ACCT_df

,SUBJECT,NBR,PROF,TOTAL,A+,A,A-,B+,B,B-,C+,C,C-,D,F,W,AVG GPA
0,ACCT,100,"HO, V",28,0,11,2,1,3,3,0,3,0,0,0,5,3.383
1,ACCT,101,"CHAN, J",29,0,13,2,0,4,5,0,0,1,0,0,3,3.464
2,ACCT,101,"RUTHIZER, S",50,2,9,14,6,4,5,0,1,0,3,2,3,3.176
3,ACCT,101,"GRUZA, M",45,1,2,3,1,5,0,6,0,0,0,0,25,3.067
4,ACCT,101,"FEISULLIN, A",45,4,6,1,7,5,0,6,9,1,1,0,4,2.908
5,ACCT,101,"COWAN DOCKERY, M",45,6,1,1,4,3,2,2,11,0,0,1,9,2.771
6,ACCT,101,"THALER, M",45,0,0,4,5,7,4,5,9,0,1,0,8,2.674
7,ACCT,101,"SOLARSH, E",45,3,4,2,3,2,3,1,6,7,0,2,9,2.594
8,ACCT,101,"SOLARSH, E",45,4,1,3,3,7,2,0,8,5,0,3,6,2.553
9,ACCT,101,"DAUBER, N",50,2,0,1,3,7,2,2,7,3,6,6,10,1.992
10,ACCT,102,"FEISULLIN, A",40,7,1,2,2,6,6,3,1,4,0,0,8,2.997
11,ACCT,102,"RUTHIZER, S",46,1,1,6,12,7,7,4,3,0,4,0,1,2.864
12,ACCT,102,"RUBIN, M",22,2,2,0,2,2,3,1,1,4,3,0,2,2.540
13,ACCT,102,"DAVID, A",29,0,2,2,1,6,2,5,4,0,3,1,3,2.485
14,ACCT,102,"GRUZA, M",15,1,1,0,2,0,1,0,0,0,0,2,8,2.471
15,ACCT,102,"DAVID, A",34,0,2,1,3,7,4,2,6,3,2,2,2,2.409
16,ACCT,201,"HEASLIP, K",36,1,6,4,1,2,4,5,4,3,1,1,4,2.766
17,ACCT,201,"HEASLIP, K",12,0,0,1,0,0,4,0,0,4,1,0,2,2.230
18,ACCT,201,"COWAN DOCKERY, M",21,0,1,0,0,0,0,4,9,0,0,0,7,2.229
19,ACCT,201,"MAZZO, M",36,0,3,0,2,4,1,7,0,0,0,7,12,2.058
20,ACCT,202,"KUMAR, V",11,0,5,0,0,0,0,0,0,0,0,0,6,4.000
21,ACCT,202,"ROSANO, E",34,1,14,0,1,10,0,3,2,0,0,1,2,3.256
22,ACCT,202,"SCHWALB, H",16,0,2,0,6,0,2,0,2,0,1,0,3,2.938
23,ACCT,202,"SCHWALB, H",18,0,2,1,2,3,2,0,4,0,0,0,4,2.907
24,ACCT,202,"ROSANO, E",28,3,8,0,2,2,0,1,6,0,1,3,2,2.765
25,ACCT,202,"HEASLIP, K",31,1,0,2,3,2,2,2,3,1,1,3,10,2.300
26,ACCT,261,"STEIN, R",44,1,9,7,10,4,0,0,0,0,0,0,7,3.577
27,ACCT,261,"STEIN, R",25,3,0,8,5,7,2,0,0,0,0,0,0,3.380
28,ACCT,261,"ALTMAN, J",45,2,6,5,8,6,6,4,4,0,1,1,2,3.007
29,ACCT,261,"ALTMAN, J",39,0,0,4,10,7,3,3,5,0,3,2,2,2.616
30,ACCT,261,"SEYMORE, J",11,0,2,1,1,0,1,1,2,1,0,1,1,2.570
31,ACCT,261,"LEIBOWICZ, B",43,1,2,2,0,3,6,3,13,0,8,1,3,2.192
32,ACCT,261,"LEIBOWICZ, B",38,0,1,1,2,5,0,4,10,0,6,3,2,2.016
33,ACCT,305,"COHEN, M",45,0,13,6,8,5,7,0,1,0,0,1,4,3.329
34,ACCT,305,"SUN, F",27,0,13,5,0,1,1,1,2,0,1,2,0,3.212
35,ACCT,305,"QURESHI, A",27,3,2,3,4,4,3,0,5,0,0,1,2,2.976
36,ACCT,305,"COHEN, M",31,1,1,0,9,4,4,3,3,0,0,0,6,2.936
37,ACCT,306,"ADELBERG, A",35,12,16,1,0,0,1,1,0,0,0,0,3,3.894
38,ACCT,306,"ADELBERG, A",34,7,6,4,6,10,0,0,0,0,0,0,1,3.533
39,ACCT,306,"STEVENS, M",32,0,1,1,4,7,9,5,5,0,0,0,0,2.741
40,ACCT,306,"STEVENS, M",18,0,1,0,2,4,5,4,0,1,0,1,0,2.611
41,ACCT,311,"BALKARAN, D",27,0,3,6,5,2,2,1,2,0,1,1,4,3.017
42,ACCT,311,"SATENSTEIN, J",31,5,3,0,4,4,1,2,10,0,1,1,0,2.758
43,ACCT,311,"SATENSTEIN, J",31,3,3,1,0,3,5,2,8,0,3,2,1,2.460
44,ACCT,311,"HUANG, Q",12,1,1,0,1,1,2,1,1,0,2,1,1,2.364
45,ACCT,321,"SOLIERI, S",29,9,4,4,1,2,1,1,4,0,0,1,2,3.300
46,ACCT,321,"FITZSIMONS, S",13,0,0,0,4,5,1,1,1,0,0,0,1,2.933
47,ACCT,321,"KUMAR, V",29,0,2,0,0,19,0,0,6,0,0,0,2,2.852
48,ACCT,321,"DAUBER, N",47,0,4,3,3,11,3,2,6,1,10,4,0,2.264
49,ACCT,322,"QAMAR, Z",14,0,3,4,2,4,0,0,0,0,0,0,1,3.492
50,ACCT,322,"QAMAR, Z",15,1,5,0,2,4,2,1,0,0,0,0,0,3.353
51,ACCT,322,"DAUBER, N",30,6,1,1,1,3,6,6,5,0,1,0,0,2.833
52,ACCT,322,"HITZIG, N",11,0,1,0,0,2,0,3,2,0,0,0,3,2.613
53,ACCT,322,"HITZIG, N",10,0,1,0,2,2,2,0,1,0,2,0,0,2.600
54,ACCT,341,"SOLIERI, S",23,6,3,1,2,2,2,1,3,0,0,2,1,3.000
55,ACCT,343,"QURESHI, A",34,1,29,0,0,0,0,0,0,0,0,0,4,4.000
56,ACCT,350,"SILVERMAN, A",20,3,1,0,1,3,1,3,5,0,0,0,3,2.818
57,ACCT,362,"KATZ, J",29,7,5,2,1,4,2,2,4,0,0,2,0,3.059
58,ACCT,362,"ALTMAN, J",21,1,3,2,1,8,2,0,3,0,1,0,0,3.005
59,ACCT,363,"HERCZOG, L",13,0,5,4,4,0,0,0,0,0,0,0,0,3.692
60,ACCT,363,"LINN, D",13,0,4,1,1,2,0,1,1,1,0,0,1,3.182
61,ACCT,367,"BLUMENFRUCHT, I",19,2,4,5,2,1,1,2,0,0,0,0,1,3.494
62,ACCT,367,"BARONE, E",35,2,6,5,5,6,1,3,5,0,0,2,0,2.989
63,ACCT,367,"BLUMENFRUCHT, I",36,4,2,2,4,5,7,6,4,0,0,0,1,2.950
64,ACCT,367,"BARONE, E",20,3,1,1,2,4,0,4,3,0,2,0,0,2.775
65,ACCT,367,"CALAMARI, J",27,2,2,1,3,4,2,3,6,2,1,0,1,2.704
66,ACCT,367,"LEIBOWICZ, B",26,1,2,2,1,3,3,2,5,0,2,0,3,2.686
67,ACCT,372,"BALKARAN, D",45,0,7,8,10,10,3,0,3,0,0,1,3,3.207
68,ACCT,372,"XIAO, J",22,1,1,4,1,3,3,1,4,1,1,0,2,2.810
69,ACCT,372,"XIAO, J",16,1,0,1,0,5,0,4,0,1,2,1,1,2.373
70,ACCT,372,"SILVERMAN, A",37,4,2,1,2,6,2,5,3,0,3,7,2,2.234
83,ACCT,362W,"LINN, D",25,0,3,4,4,3,1,2,1,1,0,0,2,3.158
84,ACCT,362W,"SEYMORE, J",12,0,1,1,2,2,1,0,2,0,0,0,3,3.000

In [9]:
ACCT_df.shape

(73, 17)